---
title: "Quipo"
---

This website was build for share information about programming and statistics in agricultural and biological areas using free and open source softwares.

# Softwares used for develop

- [R](https://cran.rstudio.com/)
- [R Studio](https://www.rstudio.com/products/rstudio/download/)
- [Mendely](https://www.mendeley.com/)
- [Github desktop](https://desktop.github.com/)

# Projects

## **GerminaR** R package (*realesed in CRAN*)

GerminaR is a R package development for study the germination process for ecophysiological, agronomic and biological studies. This package has their interactive app  **GerminaQuant for R** for statistical and graphic analysis of germination.


<!-- ## **sapiens** R package (*in progress*) -->

<!-- Sapiens is package created to deploy interactive application for scientific research using multiples packages available in CRAN. At the moment the package have 3 apps:  -->


## **FieldBook** (*realesed*) 

Fieldbook is a interactive app for data analysis for research experiments with different statistical and multivariate analysis and perform for high quality graphics for scientific research.

## **Elisios** (*realesed*)

Elisios is a web application develop for calculate the crops water requirements according the weather information. Elisios will have the possibility to connect at meteorological station based in arduino.

## **Wanuy** (*in progress*)

Wanuy help to calculate the cost and management of the crop fertilization, according the requirements if the crops.


<!-- ## **Quipu 2.0** (*in progress*) -->

<!-- Quipu 2.0 is a book base in experience with data manipulation, collection and analysis with R and using others free softwares. These book will be write en Spanish, because there are a many people interest in learn R but a lot the information are in English. -->


```{r, echo=FALSE}
shiny::includeHTML("footer.html")
```
