---
title: "Marco Ético Quipo"
---

**QUIPO** es una empresa ética comprometida con el rol que le corresponde ante la sociedad y el ambiente.  Para los fundadores el mayor anhelo es formar gestores de cambio. 

##Responsabilidad Social.

 **QUIPO** dirige su negocio al desarrollo de  innovación y habilidad humanas, bajo las directrices internacionales:
 
 *Organización de las Naciones Unidas* _ONU_.
 
 *Organización internacional del Trabajo* _OIT_.
 
 *Organización para la coperación y el desarrollo económico* _OCDE_.
 
 <!--La responsabilidad social es parte del compromiso empresarial, atraves de un plan estratégico corporativo.-->

**QUIPO** direcciona sus fuerzas al posicionamiento de su marca con entrega de valor, servicios y productos; ser eficaz con los recursos económicos, y diferenciarse con innovación tecnológica de avanzada. Todo lo anteriormente señalado  no sería posible sin politicas de responsabilidad social y ambiental, dirigidas a la generación de empleos de calidad, y desarrollo humano.

## Derivados de la política empresarial.

###Comunicación.

Nuestro ideal, _Marco Ético_,  nace de la voluntad de integrar **QUIPO** -Empleados, accionistas, Instituciones publicas y sociedad, Clientes y proveedores- nuestro compromiso es tener un canal de comunicación (bidireccional) constante, horizontal, y siempre abierta;  con el fín de alcanzar acuerdos de puntos de interés no siempre coincidentes. 


###Acción ética.

 **QUIPO**  promoverá el comportamiento ejemplar ántes que prohibir conductas. El comportamiento resposanble deviene del accionar ético ante la sociedad,


###Aporte a sus empleados

1. Identifica y transmite modelos de comportamiento éticos.

2. Refuerza sus actitudes y compromiso con sus decisiones.

3. Aleinta a comprometerse con las consecuencias de sus actos.

4. Elentar a defender la libertades humanas.

5. Inspirar la búsqueda de la excelencia profesional.

###El empleado como Fuerza moral.

1. Asumir las propias acciones si importar, con sus consecuencias, sin pensar en el que dirán.

2. Ser proactivos ante posibles situaciones de confrontación.

3. Tomar como uno los objetivos del equipo, por encima de uno mismo.

###Centro de gestión ética.

El centro de gestión ética se encarga de:

1. Velar e implementar el marco ético.

2. Cumplimiento del marco ético.

3. Revisar, y vigilancia del marco ético.

4. Dar pie a las demandas, tratamiento y solución de conflictos.

5. Representar a los grupos de interés.


##Nuestro Ideal

###Derechos humanos
 
 1. La empresa respeta y apoya la protección de los derechos humanos proclamados internacionalmente.
 
 2. Rechazamos todo accionar, comportamiento ó actitud que transgrieda los derechos fundamentales y constitucionales.
 
###Estándares laborales
 
 1. La empresa respeta la libertad de asociación.
 
 2. Elimiar toda forma de trabajo forzoso y obligatorio.
 
 3. Abolición del trabajo infantil y trata de personas.
 
 4. Eliminar la discriminación en todas sus formas.
 
###Conservación del Ambiente.
 
 1. Colaborar con los desafios ambientales actuales y aquellos por venir.
 
 2. Apoyar y adoptar medidas que promuevan la conservacion ambiental.
 
 3. Alentar el desarrollo y disusión de tecnologías que promuevan la conservación del medio.
 
 